### ISSUE TITLE
Fix release changelog

### ISSUE THREAD

**Issue by alexashley** [rode/rode-ui#71]
Release of [`v0.6.0`](https://github.com/rode/rode-ui/releases/tag/v0.6.0) has a changelog that just says "no changes".

In #70 we tried to revert to what was likely the version that during the previous release, but that didn't work either.

**Comment by pickjasmine** [comment]
@aalsabag manually updated the release notes for [v0.5.0](https://github.com/rode/rode-ui/releases/tag/v0.5.0). He is/was aware that this was happening and he said that [it is being worked on](https://liatrio.slack.com/archives/C01CF09RJHZ/p1619028441222300?thread_ts=1619028051.221800&cid=C01CF09RJHZ)
